In [1]:
import os
os.chdir('../')
%pwd

'/home/megh/AI/Projects/Semantic_Segmentation_for_self_driving_cars'

In [2]:
import tensorflow as tf

2023-09-28 13:14:47.119612: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-28 13:14:47.755244: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
tf.__version__

'2.13.1'

In [4]:
import box

In [5]:
from src.components.data_preparation import DataIngestion
from src.components.data_preprocesing import DataPreprocessing
from src.components.callbacks import PrepareCallback
from src.components.model import PrepareModel
from src.config.configuration import ConfigurationManager
from src.entity.config_entity import DataIngestionConfig, PrepareCallbackConfig, PrepareModelConfig


In [6]:
import glob

In [7]:
from src.entity.config_entity import DataPreprocessingConfig

In [8]:
try:
    config = ConfigurationManager()
    prepare_data_config = config.get_data_ingestion_config()

    prepare_dataset = DataIngestion(config=prepare_data_config)
    imgs_list, masks_list = prepare_dataset.prepare_data()

    preprocessing_config = config.get_data_processing_config()
    preprocessing = DataPreprocessing(preprocessing_config,imgs_list, masks_list)
    train, val = preprocessing.data_preprocessing()

except Exception as e:
    raise e



[2023-09-28 13:14:57,369: INFO: common: yaml fileconfig.yamlloaded Successfully]
[2023-09-28 13:14:57,373: INFO: common: yaml fileparams.yamlloaded Successfully]
[2023-09-28 13:14:57,374: INFO: common: created directory at:artifacts]
[2023-09-28 13:14:57,375: INFO: common: created directory at:/media/Ubuntu/meg/mlprojects/Semantic_Segmentation_for_self_driving_cars/archive]


2023-09-28 13:14:58.983544: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2023-09-28 13:14:58.983589: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:168] retrieving CUDA diagnostic information for host: megh
2023-09-28 13:14:58.983594: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:175] hostname: megh
2023-09-28 13:14:58.983718: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:199] libcuda reported version is: 535.113.1
2023-09-28 13:14:58.983732: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:203] kernel reported version is: 535.86.10
2023-09-28 13:14:58.983736: E tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:312] kernel version 535.86.10 does not match DSO version 535.113.1 -- cannot find working devices in this configuration


In [9]:
try:
    config = ConfigurationManager()
    prepare_model_config = config.get_prepare_model_config()
    prepare_model = PrepareModel(prepare_model_config)
    model = prepare_model.unet_model()
    model.summary()
except Exception as e:
    raise e

[2023-09-28 13:15:21,974: INFO: common: yaml fileconfig.yamlloaded Successfully]
[2023-09-28 13:15:21,977: INFO: common: yaml fileparams.yamlloaded Successfully]
[2023-09-28 13:15:21,978: INFO: common: created directory at:artifacts]
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 192, 256, 3)]        0         []                            
                                                                                                  
 conv2d (Conv2D)             (None, 192, 256, 32)         896       ['input_1[0][0]']             
                                                                                                  
 batch_normalization (Batch  (None, 192, 256, 32)         128       ['conv2d[0][0]']              
 Normalization)                                           

In [10]:
from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class ModelTrainingConfig:
    epochs: int


In [11]:
from src.constants import *
from src.utils.common import read_yaml, create_directories
from box import ConfigBox
from src import logger

In [10]:
try:
    config = ConfigurationManager()
    prepare_callbacks_config= config.get_prepare_callback_config()
    prepare_callbacks= PrepareCallback(config = prepare_callbacks_config)
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
except Exception as e:
    raise e

[2023-09-28 13:18:27,293: INFO: common: yaml fileconfig.yamlloaded Successfully]
[2023-09-28 13:18:27,295: INFO: common: yaml fileparams.yamlloaded Successfully]
[2023-09-28 13:18:27,297: INFO: common: created directory at:artifacts]
[2023-09-28 13:18:27,298: INFO: common: created directory at:artifacts/callbacks]
[2023-09-28 13:18:27,299: INFO: common: created directory at:artifacts/callbacks/checkpoints]
[2023-09-28 13:18:27,300: INFO: common: created directory at:artifacts/callbacks/tensorboard_log_dir]
artifacts/callbacks/tensorboard_log_dir/tb_logs_at_2023-09-28-13-18-27


In [12]:
import tensorflow as tf

In [11]:
model1 = model.compile(optimizer=tf.keras.optimizers.legacy.Adam(),
                    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [15]:
tf.__version__

'2.13.1'

In [14]:
for i , j in tuple(train)[:2]:
    print(i)
    print(j)

tf.Tensor(
[[[[0.2392157  0.38823533 0.5686275 ]
   [0.2392157  0.39607847 0.5686275 ]
   [0.2392157  0.39607847 0.5686275 ]
   ...
   [0.6431373  0.6156863  0.5254902 ]
   [0.6313726  0.60784316 0.5137255 ]
   [0.62352943 0.6        0.5058824 ]]

  [[0.2392157  0.39607847 0.5686275 ]
   [0.2392157  0.38823533 0.5686275 ]
   [0.2392157  0.38823533 0.5686275 ]
   ...
   [0.62352943 0.6        0.5058824 ]
   [0.6117647  0.5882353  0.49411768]
   [0.60784316 0.5882353  0.49411768]]

  [[0.2392157  0.38823533 0.5686275 ]
   [0.2392157  0.39607847 0.57254905]
   [0.2392157  0.39607847 0.57254905]
   ...
   [0.5921569  0.5647059  0.47058827]
   [0.5803922  0.5529412  0.45882356]
   [0.59607846 0.5686275  0.4784314 ]]

  ...

  [[0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.0509804 ]
   ...
   [0.         0.         0.        ]
   [0.0509804  0.0509804  0.        ]
   [0.0509804  0.0509804  0.        ]]

  [[0.         0.         0.050980

In [12]:
model_history1 = model.fit(train, validation_data=val, epochs=1, callbacks=callback_list)

: 

In [ ]:
model_history1.save('model.h5')